-- Tạo dữ liệu cho 50 chủ đề từ vựng TOEIC
INSERT INTO question_groups (title, question_type, part) VALUES
('Office and Business', 'VOCABULARY', 0),
('Travel and Transportation', 'VOCABULARY', 0),
('Employment and Job Hunting', 'VOCABULARY', 0),
('Marketing and Sales', 'VOCABULARY', 0),
('Finance and Banking', 'VOCABULARY', 0),
('Health and Medicine', 'VOCABULARY', 0),
('Technology and Internet', 'VOCABULARY', 0),
('Manufacturing and Production', 'VOCABULARY', 0),
('Entertainment and Media', 'VOCABULARY', 0),
('Food and Dining', 'VOCABULARY', 0),
('Retail and Shopping', 'VOCABULARY', 0),
('Customer Service', 'VOCABULARY', 0),
('Real Estate and Property', 'VOCABULARY', 0),
('Contracts and Legal', 'VOCABULARY', 0),
('Meetings and Presentations', 'VOCABULARY', 0),
('Education and Training', 'VOCABULARY', 0),
('Mail and Shipping', 'VOCABULARY', 0),
('Airport and Flight', 'VOCABULARY', 0),
('Hotel and Accommodation', 'VOCABULARY', 0),
('Personnel and HR', 'VOCABULARY', 0),
('Computers and Software', 'VOCABULARY', 0),
('Telephone and Communication', 'VOCABULARY', 0),
('Events and Conferences', 'VOCABULARY', 0),
('Energy and Environment', 'VOCABULARY', 0),
('Time and Schedule', 'VOCABULARY', 0),
('Sports and Recreation', 'VOCABULARY', 0),
('Weather and Climate', 'VOCABULARY', 0),
('Construction and Architecture', 'VOCABULARY', 0),
('Agriculture and Farming', 'VOCABULARY', 0),
('Automotive and Transportation', 'VOCABULARY', 0),
('Science and Research', 'VOCABULARY', 0),
('Art and Design', 'VOCABULARY', 0),
('Insurance and Benefits', 'VOCABULARY', 0),
('Management and Leadership', 'VOCABULARY', 0),
('Statistics and Data Analysis', 'VOCABULARY', 0),
('Clothing and Fashion', 'VOCABULARY', 0),
('Government and Politics', 'VOCABULARY', 0),
('Negotiations and Agreements', 'VOCABULARY', 0),
('Accounting and Auditing', 'VOCABULARY', 0),
('Quality Control', 'VOCABULARY', 0),
('Logistics and Supply Chain', 'VOCABULARY', 0),
('Public Relations', 'VOCABULARY', 0),
('Safety and Security', 'VOCABULARY', 0),
('Advertising and Promotion', 'VOCABULARY', 0),
('Economics and Trade', 'VOCABULARY', 0),
('Charity and Non-profit', 'VOCABULARY', 0),
('International Business', 'VOCABULARY', 0),
('Teamwork and Collaboration', 'VOCABULARY', 0),
('Healthcare Administration', 'VOCABULARY', 0),
('Company Structure', 'VOCABULARY', 0); 